#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestAPI
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="API_QuanLyBanQuanAo")]
	public partial class DbQuanLyBanQuanAoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblAccount(tblAccount instance);
    partial void UpdatetblAccount(tblAccount instance);
    partial void DeletetblAccount(tblAccount instance);
    partial void InserttblChatLieu(tblChatLieu instance);
    partial void UpdatetblChatLieu(tblChatLieu instance);
    partial void DeletetblChatLieu(tblChatLieu instance);
    partial void InserttblHoaDonBan(tblHoaDonBan instance);
    partial void UpdatetblHoaDonBan(tblHoaDonBan instance);
    partial void DeletetblHoaDonBan(tblHoaDonBan instance);
    partial void InserttblHoaDonNhap(tblHoaDonNhap instance);
    partial void UpdatetblHoaDonNhap(tblHoaDonNhap instance);
    partial void DeletetblHoaDonNhap(tblHoaDonNhap instance);
    partial void InserttblKhachHang(tblKhachHang instance);
    partial void UpdatetblKhachHang(tblKhachHang instance);
    partial void DeletetblKhachHang(tblKhachHang instance);
    partial void InserttblMauSac(tblMauSac instance);
    partial void UpdatetblMauSac(tblMauSac instance);
    partial void DeletetblMauSac(tblMauSac instance);
    partial void InserttblNhaCungCap(tblNhaCungCap instance);
    partial void UpdatetblNhaCungCap(tblNhaCungCap instance);
    partial void DeletetblNhaCungCap(tblNhaCungCap instance);
    partial void InserttblNV(tblNV instance);
    partial void UpdatetblNV(tblNV instance);
    partial void DeletetblNV(tblNV instance);
    partial void InserttblSanPham(tblSanPham instance);
    partial void UpdatetblSanPham(tblSanPham instance);
    partial void DeletetblSanPham(tblSanPham instance);
    partial void InserttblSize(tblSize instance);
    partial void UpdatetblSize(tblSize instance);
    partial void DeletetblSize(tblSize instance);
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    #endregion
		
		public DbQuanLyBanQuanAoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbQuanLyBanQuanAoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbQuanLyBanQuanAoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbQuanLyBanQuanAoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblAccount> tblAccounts
		{
			get
			{
				return this.GetTable<tblAccount>();
			}
		}
		
		public System.Data.Linq.Table<tblChatLieu> tblChatLieus
		{
			get
			{
				return this.GetTable<tblChatLieu>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietHDB> tblChiTietHDBs
		{
			get
			{
				return this.GetTable<tblChiTietHDB>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietHDN> tblChiTietHDNs
		{
			get
			{
				return this.GetTable<tblChiTietHDN>();
			}
		}
		
		public System.Data.Linq.Table<tblHoaDonBan> tblHoaDonBans
		{
			get
			{
				return this.GetTable<tblHoaDonBan>();
			}
		}
		
		public System.Data.Linq.Table<tblHoaDonNhap> tblHoaDonNhaps
		{
			get
			{
				return this.GetTable<tblHoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<tblKhachHang> tblKhachHangs
		{
			get
			{
				return this.GetTable<tblKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<tblMauSac> tblMauSacs
		{
			get
			{
				return this.GetTable<tblMauSac>();
			}
		}
		
		public System.Data.Linq.Table<tblNhaCungCap> tblNhaCungCaps
		{
			get
			{
				return this.GetTable<tblNhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<tblNV> tblNVs
		{
			get
			{
				return this.GetTable<tblNV>();
			}
		}
		
		public System.Data.Linq.Table<tblSanPham> tblSanPhams
		{
			get
			{
				return this.GetTable<tblSanPham>();
			}
		}
		
		public System.Data.Linq.Table<tblSize> tblSizes
		{
			get
			{
				return this.GetTable<tblSize>();
			}
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPBan", IsComposable=true)]
		public IQueryable<SPBanResult> SPBan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSP", DbType="NVarChar(50)")] string tenSP)
		{
			return this.CreateMethodCallQuery<SPBanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam, tenSP);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPBanBDTron", IsComposable=true)]
		public IQueryable<SPBanBDTronResult> SPBanBDTron([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<SPBanBDTronResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPNhap", IsComposable=true)]
		public IQueryable<SPNhapResult> SPNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenSP", DbType="NVarChar(50)")] string tenSP)
		{
			return this.CreateMethodCallQuery<SPNhapResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam, tenSP);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPNhapBDTron", IsComposable=true)]
		public IQueryable<SPNhapBDTronResult> SPNhapBDTron([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<SPNhapBDTronResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TienBanNam", IsComposable=true)]
		public IQueryable<TienBanNamResult> TienBanNam([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<TienBanNamResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TienNhapNam", IsComposable=true)]
		public IQueryable<TienNhapNamResult> TienNhapNam([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nam", DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<TienNhapNamResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAccount")]
	public partial class tblAccount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _Username;
		
		private string _Password;
		
		private string _Email;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntityRef<tblKhachHang> _tblKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblAccount()
		{
			this._tblKhachHang = default(EntityRef<tblKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblAccount", Storage="_tblKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tblKhachHang tblKhachHang
		{
			get
			{
				return this._tblKhachHang.Entity;
			}
			set
			{
				tblKhachHang previousValue = this._tblKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhachHang.Entity = null;
						previousValue.tblAccount = null;
					}
					this._tblKhachHang.Entity = value;
					if ((value != null))
					{
						value.tblAccount = this;
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tblKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChatLieu")]
	public partial class tblChatLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChatLieu;
		
		private string _TenChatLieu;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChatLieuChanging(string value);
    partial void OnMaChatLieuChanged();
    partial void OnTenChatLieuChanging(string value);
    partial void OnTenChatLieuChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblChatLieu()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChatLieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChatLieu
		{
			get
			{
				return this._MaChatLieu;
			}
			set
			{
				if ((this._MaChatLieu != value))
				{
					this.OnMaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._MaChatLieu = value;
					this.SendPropertyChanged("MaChatLieu");
					this.OnMaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChatLieu", DbType="NVarChar(50)")]
		public string TenChatLieu
		{
			get
			{
				return this._TenChatLieu;
			}
			set
			{
				if ((this._TenChatLieu != value))
				{
					this.OnTenChatLieuChanging(value);
					this.SendPropertyChanging();
					this._TenChatLieu = value;
					this.SendPropertyChanged("TenChatLieu");
					this.OnTenChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChatLieu_tblSanPham", Storage="_tblSanPhams", ThisKey="MaChatLieu", OtherKey="MaChatLieu")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblChatLieu = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblChatLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietHDB")]
	public partial class tblChiTietHDB
	{
		
		private string _MaHDB;
		
		private string _MaSP;
		
		private System.Nullable<int> _SLBan;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private System.Nullable<int> _IsDeleted;
		
		public tblChiTietHDB()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDB", DbType="NVarChar(50)")]
		public string MaHDB
		{
			get
			{
				return this._MaHDB;
			}
			set
			{
				if ((this._MaHDB != value))
				{
					this._MaHDB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(50)")]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this._MaSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLBan", DbType="Int")]
		public System.Nullable<int> SLBan
		{
			get
			{
				return this._SLBan;
			}
			set
			{
				if ((this._SLBan != value))
				{
					this._SLBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietHDN")]
	public partial class tblChiTietHDN
	{
		
		private string _MaHDN;
		
		private string _MaSP;
		
		private int _SLNhap;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private System.Nullable<int> _IsDeleted;
		
		public tblChiTietHDN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaHDN
		{
			get
			{
				return this._MaHDN;
			}
			set
			{
				if ((this._MaHDN != value))
				{
					this._MaHDN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this._MaSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLNhap", DbType="Int NOT NULL")]
		public int SLNhap
		{
			get
			{
				return this._SLNhap;
			}
			set
			{
				if ((this._SLNhap != value))
				{
					this._SLNhap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHoaDonBan")]
	public partial class tblHoaDonBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDB;
		
		private string _MaNV;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayBan;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntityRef<tblKhachHang> _tblKhachHang;
		
		private EntityRef<tblNV> _tblNV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDBChanging(string value);
    partial void OnMaHDBChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblHoaDonBan()
		{
			this._tblKhachHang = default(EntityRef<tblKhachHang>);
			this._tblNV = default(EntityRef<tblNV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDB", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDB
		{
			get
			{
				return this._MaHDB;
			}
			set
			{
				if ((this._MaHDB != value))
				{
					this.OnMaHDBChanging(value);
					this.SendPropertyChanging();
					this._MaHDB = value;
					this.SendPropertyChanged("MaHDB");
					this.OnMaHDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(50)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._tblKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBan
		{
			get
			{
				return this._NgayBan;
			}
			set
			{
				if ((this._NgayBan != value))
				{
					this.OnNgayBanChanging(value);
					this.SendPropertyChanging();
					this._NgayBan = value;
					this.SendPropertyChanged("NgayBan");
					this.OnNgayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblHoaDonBan", Storage="_tblKhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public tblKhachHang tblKhachHang
		{
			get
			{
				return this._tblKhachHang.Entity;
			}
			set
			{
				tblKhachHang previousValue = this._tblKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._tblKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKhachHang.Entity = null;
						previousValue.tblHoaDonBans.Remove(this);
					}
					this._tblKhachHang.Entity = value;
					if ((value != null))
					{
						value.tblHoaDonBans.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("tblKhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNV_tblHoaDonBan", Storage="_tblNV", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNV tblNV
		{
			get
			{
				return this._tblNV.Entity;
			}
			set
			{
				tblNV previousValue = this._tblNV.Entity;
				if (((previousValue != value) 
							|| (this._tblNV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNV.Entity = null;
						previousValue.tblHoaDonBans.Remove(this);
					}
					this._tblNV.Entity = value;
					if ((value != null))
					{
						value.tblHoaDonBans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("tblNV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHoaDonNhap")]
	public partial class tblHoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHDN;
		
		private string _MaNV;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private string _MaNCC;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntityRef<tblNhaCungCap> _tblNhaCungCap;
		
		private EntityRef<tblNV> _tblNV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDNChanging(string value);
    partial void OnMaHDNChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblHoaDonNhap()
		{
			this._tblNhaCungCap = default(EntityRef<tblNhaCungCap>);
			this._tblNV = default(EntityRef<tblNV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDN", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHDN
		{
			get
			{
				return this._MaHDN;
			}
			set
			{
				if ((this._MaHDN != value))
				{
					this.OnMaHDNChanging(value);
					this.SendPropertyChanging();
					this._MaHDN = value;
					this.SendPropertyChanged("MaHDN");
					this.OnMaHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(50)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblNhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblHoaDonNhap", Storage="_tblNhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tblNhaCungCap tblNhaCungCap
		{
			get
			{
				return this._tblNhaCungCap.Entity;
			}
			set
			{
				tblNhaCungCap previousValue = this._tblNhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tblNhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhaCungCap.Entity = null;
						previousValue.tblHoaDonNhaps.Remove(this);
					}
					this._tblNhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tblHoaDonNhaps.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tblNhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNV_tblHoaDonNhap", Storage="_tblNV", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNV tblNV
		{
			get
			{
				return this._tblNV.Entity;
			}
			set
			{
				tblNV previousValue = this._tblNV.Entity;
				if (((previousValue != value) 
							|| (this._tblNV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNV.Entity = null;
						previousValue.tblHoaDonNhaps.Remove(this);
					}
					this._tblNV.Entity = value;
					if ((value != null))
					{
						value.tblHoaDonNhaps.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("tblNV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKhachHang")]
	public partial class tblKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Anh;
		
		private string _GioiTinh;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntityRef<tblAccount> _tblAccount;
		
		private EntitySet<tblHoaDonBan> _tblHoaDonBans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblKhachHang()
		{
			this._tblAccount = default(EntityRef<tblAccount>);
			this._tblHoaDonBans = new EntitySet<tblHoaDonBan>(new Action<tblHoaDonBan>(this.attach_tblHoaDonBans), new Action<tblHoaDonBan>(this.detach_tblHoaDonBans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(50)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblAccount", Storage="_tblAccount", ThisKey="MaKH", OtherKey="MaKH", IsUnique=true, IsForeignKey=false)]
		public tblAccount tblAccount
		{
			get
			{
				return this._tblAccount.Entity;
			}
			set
			{
				tblAccount previousValue = this._tblAccount.Entity;
				if (((previousValue != value) 
							|| (this._tblAccount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblAccount.Entity = null;
						previousValue.tblKhachHang = null;
					}
					this._tblAccount.Entity = value;
					if ((value != null))
					{
						value.tblKhachHang = this;
					}
					this.SendPropertyChanged("tblAccount");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKhachHang_tblHoaDonBan", Storage="_tblHoaDonBans", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<tblHoaDonBan> tblHoaDonBans
		{
			get
			{
				return this._tblHoaDonBans;
			}
			set
			{
				this._tblHoaDonBans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHoaDonBans(tblHoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = this;
		}
		
		private void detach_tblHoaDonBans(tblHoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tblKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMauSac")]
	public partial class tblMauSac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMauSac;
		
		private string _TenMau;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMauSacChanging(string value);
    partial void OnMaMauSacChanged();
    partial void OnTenMauChanging(string value);
    partial void OnTenMauChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblMauSac()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMauSac", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMauSac
		{
			get
			{
				return this._MaMauSac;
			}
			set
			{
				if ((this._MaMauSac != value))
				{
					this.OnMaMauSacChanging(value);
					this.SendPropertyChanging();
					this._MaMauSac = value;
					this.SendPropertyChanged("MaMauSac");
					this.OnMaMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMau", DbType="NVarChar(50)")]
		public string TenMau
		{
			get
			{
				return this._TenMau;
			}
			set
			{
				if ((this._TenMau != value))
				{
					this.OnTenMauChanging(value);
					this.SendPropertyChanging();
					this._TenMau = value;
					this.SendPropertyChanged("TenMau");
					this.OnTenMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMauSac_tblSanPham", Storage="_tblSanPhams", ThisKey="MaMauSac", OtherKey="MaMauSac")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblMauSac = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblMauSac = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhaCungCap")]
	public partial class tblNhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntitySet<tblHoaDonNhap> _tblHoaDonNhaps;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblNhaCungCap()
		{
			this._tblHoaDonNhaps = new EntitySet<tblHoaDonNhap>(new Action<tblHoaDonNhap>(this.attach_tblHoaDonNhaps), new Action<tblHoaDonNhap>(this.detach_tblHoaDonNhaps));
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblHoaDonNhap", Storage="_tblHoaDonNhaps", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tblHoaDonNhap> tblHoaDonNhaps
		{
			get
			{
				return this._tblHoaDonNhaps;
			}
			set
			{
				this._tblHoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblSanPham", Storage="_tblSanPhams", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHoaDonNhaps(tblHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = this;
		}
		
		private void detach_tblHoaDonNhaps(tblHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = null;
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblNhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNV")]
	public partial class tblNV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _TenNV;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _Anh;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _ChucVu;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntitySet<tblHoaDonBan> _tblHoaDonBans;
		
		private EntitySet<tblHoaDonNhap> _tblHoaDonNhaps;
		
		private EntityRef<tblUser> _tblUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblNV()
		{
			this._tblHoaDonBans = new EntitySet<tblHoaDonBan>(new Action<tblHoaDonBan>(this.attach_tblHoaDonBans), new Action<tblHoaDonBan>(this.detach_tblHoaDonBans));
			this._tblHoaDonNhaps = new EntitySet<tblHoaDonNhap>(new Action<tblHoaDonNhap>(this.attach_tblHoaDonNhaps), new Action<tblHoaDonNhap>(this.detach_tblHoaDonNhaps));
			this._tblUser = default(EntityRef<tblUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(50)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNV_tblHoaDonBan", Storage="_tblHoaDonBans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tblHoaDonBan> tblHoaDonBans
		{
			get
			{
				return this._tblHoaDonBans;
			}
			set
			{
				this._tblHoaDonBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNV_tblHoaDonNhap", Storage="_tblHoaDonNhaps", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tblHoaDonNhap> tblHoaDonNhaps
		{
			get
			{
				return this._tblHoaDonNhaps;
			}
			set
			{
				this._tblHoaDonNhaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNV_tblUser", Storage="_tblUser", ThisKey="MaNV", OtherKey="MaNV", IsUnique=true, IsForeignKey=false)]
		public tblUser tblUser
		{
			get
			{
				return this._tblUser.Entity;
			}
			set
			{
				tblUser previousValue = this._tblUser.Entity;
				if (((previousValue != value) 
							|| (this._tblUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUser.Entity = null;
						previousValue.tblNV = null;
					}
					this._tblUser.Entity = value;
					if ((value != null))
					{
						value.tblNV = this;
					}
					this.SendPropertyChanged("tblUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHoaDonBans(tblHoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tblNV = this;
		}
		
		private void detach_tblHoaDonBans(tblHoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.tblNV = null;
		}
		
		private void attach_tblHoaDonNhaps(tblHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblNV = this;
		}
		
		private void detach_tblHoaDonNhaps(tblHoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.tblNV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSanPham")]
	public partial class tblSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSP;
		
		private string _TenSP;
		
		private string _MaChatLieu;
		
		private string _MaMauSac;
		
		private string _MaSize;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _DonGiaNhap;
		
		private System.Nullable<decimal> _DonGiaBan;
		
		private string _Anh;
		
		private string _GhiChu;
		
		private string _MaNCC;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntityRef<tblChatLieu> _tblChatLieu;
		
		private EntityRef<tblMauSac> _tblMauSac;
		
		private EntityRef<tblNhaCungCap> _tblNhaCungCap;
		
		private EntityRef<tblSize> _tblSize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnMaChatLieuChanging(string value);
    partial void OnMaChatLieuChanged();
    partial void OnMaMauSacChanging(string value);
    partial void OnMaMauSacChanged();
    partial void OnMaSizeChanging(string value);
    partial void OnMaSizeChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaNhapChanging(System.Nullable<decimal> value);
    partial void OnDonGiaNhapChanged();
    partial void OnDonGiaBanChanging(System.Nullable<decimal> value);
    partial void OnDonGiaBanChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblSanPham()
		{
			this._tblChatLieu = default(EntityRef<tblChatLieu>);
			this._tblMauSac = default(EntityRef<tblMauSac>);
			this._tblNhaCungCap = default(EntityRef<tblNhaCungCap>);
			this._tblSize = default(EntityRef<tblSize>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChatLieu", DbType="NVarChar(50)")]
		public string MaChatLieu
		{
			get
			{
				return this._MaChatLieu;
			}
			set
			{
				if ((this._MaChatLieu != value))
				{
					if (this._tblChatLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChatLieuChanging(value);
					this.SendPropertyChanging();
					this._MaChatLieu = value;
					this.SendPropertyChanged("MaChatLieu");
					this.OnMaChatLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMauSac", DbType="NVarChar(50)")]
		public string MaMauSac
		{
			get
			{
				return this._MaMauSac;
			}
			set
			{
				if ((this._MaMauSac != value))
				{
					if (this._tblMauSac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMauSacChanging(value);
					this.SendPropertyChanging();
					this._MaMauSac = value;
					this.SendPropertyChanged("MaMauSac");
					this.OnMaMauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSize", DbType="NVarChar(50)")]
		public string MaSize
		{
			get
			{
				return this._MaSize;
			}
			set
			{
				if ((this._MaSize != value))
				{
					if (this._tblSize.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSizeChanging(value);
					this.SendPropertyChanging();
					this._MaSize = value;
					this.SendPropertyChanged("MaSize");
					this.OnMaSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaNhap", DbType="Money")]
		public System.Nullable<decimal> DonGiaNhap
		{
			get
			{
				return this._DonGiaNhap;
			}
			set
			{
				if ((this._DonGiaNhap != value))
				{
					this.OnDonGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._DonGiaNhap = value;
					this.SendPropertyChanged("DonGiaNhap");
					this.OnDonGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGiaBan", DbType="Money")]
		public System.Nullable<decimal> DonGiaBan
		{
			get
			{
				return this._DonGiaBan;
			}
			set
			{
				if ((this._DonGiaBan != value))
				{
					this.OnDonGiaBanChanging(value);
					this.SendPropertyChanging();
					this._DonGiaBan = value;
					this.SendPropertyChanged("DonGiaBan");
					this.OnDonGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(50)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(50)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._tblNhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChatLieu_tblSanPham", Storage="_tblChatLieu", ThisKey="MaChatLieu", OtherKey="MaChatLieu", IsForeignKey=true)]
		public tblChatLieu tblChatLieu
		{
			get
			{
				return this._tblChatLieu.Entity;
			}
			set
			{
				tblChatLieu previousValue = this._tblChatLieu.Entity;
				if (((previousValue != value) 
							|| (this._tblChatLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChatLieu.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblChatLieu.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaChatLieu = value.MaChatLieu;
					}
					else
					{
						this._MaChatLieu = default(string);
					}
					this.SendPropertyChanged("tblChatLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMauSac_tblSanPham", Storage="_tblMauSac", ThisKey="MaMauSac", OtherKey="MaMauSac", IsForeignKey=true)]
		public tblMauSac tblMauSac
		{
			get
			{
				return this._tblMauSac.Entity;
			}
			set
			{
				tblMauSac previousValue = this._tblMauSac.Entity;
				if (((previousValue != value) 
							|| (this._tblMauSac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMauSac.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblMauSac.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaMauSac = value.MaMauSac;
					}
					else
					{
						this._MaMauSac = default(string);
					}
					this.SendPropertyChanged("tblMauSac");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhaCungCap_tblSanPham", Storage="_tblNhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public tblNhaCungCap tblNhaCungCap
		{
			get
			{
				return this._tblNhaCungCap.Entity;
			}
			set
			{
				tblNhaCungCap previousValue = this._tblNhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._tblNhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhaCungCap.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblNhaCungCap.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("tblNhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSize_tblSanPham", Storage="_tblSize", ThisKey="MaSize", OtherKey="MaSize", IsForeignKey=true)]
		public tblSize tblSize
		{
			get
			{
				return this._tblSize.Entity;
			}
			set
			{
				tblSize previousValue = this._tblSize.Entity;
				if (((previousValue != value) 
							|| (this._tblSize.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSize.Entity = null;
						previousValue.tblSanPhams.Remove(this);
					}
					this._tblSize.Entity = value;
					if ((value != null))
					{
						value.tblSanPhams.Add(this);
						this._MaSize = value.MaSize;
					}
					else
					{
						this._MaSize = default(string);
					}
					this.SendPropertyChanged("tblSize");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSize")]
	public partial class tblSize : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSize;
		
		private string _TenSize;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntitySet<tblSanPham> _tblSanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSizeChanging(string value);
    partial void OnMaSizeChanged();
    partial void OnTenSizeChanging(string value);
    partial void OnTenSizeChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblSize()
		{
			this._tblSanPhams = new EntitySet<tblSanPham>(new Action<tblSanPham>(this.attach_tblSanPhams), new Action<tblSanPham>(this.detach_tblSanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSize", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSize
		{
			get
			{
				return this._MaSize;
			}
			set
			{
				if ((this._MaSize != value))
				{
					this.OnMaSizeChanging(value);
					this.SendPropertyChanging();
					this._MaSize = value;
					this.SendPropertyChanged("MaSize");
					this.OnMaSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSize", DbType="NVarChar(50)")]
		public string TenSize
		{
			get
			{
				return this._TenSize;
			}
			set
			{
				if ((this._TenSize != value))
				{
					this.OnTenSizeChanging(value);
					this.SendPropertyChanging();
					this._TenSize = value;
					this.SendPropertyChanged("TenSize");
					this.OnTenSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSize_tblSanPham", Storage="_tblSanPhams", ThisKey="MaSize", OtherKey="MaSize")]
		public EntitySet<tblSanPham> tblSanPhams
		{
			get
			{
				return this._tblSanPhams;
			}
			set
			{
				this._tblSanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblSize = this;
		}
		
		private void detach_tblSanPhams(tblSanPham entity)
		{
			this.SendPropertyChanging();
			entity.tblSize = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _Username;
		
		private string _Password;
		
		private string _Email;
		
		private System.Nullable<int> _IsDeleted;
		
		private EntityRef<tblNV> _tblNV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnIsDeletedChanging(System.Nullable<int> value);
    partial void OnIsDeletedChanged();
    #endregion
		
		public tblUser()
		{
			this._tblNV = default(EntityRef<tblNV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Int")]
		public System.Nullable<int> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNV_tblUser", Storage="_tblNV", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNV tblNV
		{
			get
			{
				return this._tblNV.Entity;
			}
			set
			{
				tblNV previousValue = this._tblNV.Entity;
				if (((previousValue != value) 
							|| (this._tblNV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNV.Entity = null;
						previousValue.tblUser = null;
					}
					this._tblNV.Entity = value;
					if ((value != null))
					{
						value.tblUser = this;
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("tblNV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _MaSP;
		
		private string _TenSP;
		
		private System.Nullable<decimal> _GiaTien;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _ThanhTien;
		
		private System.Nullable<int> _IsShopped;
		
		private string _Anh;
		
		private string _MaKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnMaSPChanging(string value);
    partial void OnMaSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnThanhTienChanging(System.Nullable<decimal> value);
    partial void OnThanhTienChanged();
    partial void OnIsShoppedChanging(System.Nullable<int> value);
    partial void OnIsShoppedChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public GioHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="NVarChar(50)")]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this.OnMaSPChanging(value);
					this.SendPropertyChanging();
					this._MaSP = value;
					this.SendPropertyChanged("MaSP");
					this.OnMaSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this.OnTenSPChanging(value);
					this.SendPropertyChanging();
					this._TenSP = value;
					this.SendPropertyChanged("TenSP");
					this.OnTenSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Money")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Money")]
		public System.Nullable<decimal> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsShopped", DbType="Int")]
		public System.Nullable<int> IsShopped
		{
			get
			{
				return this._IsShopped;
			}
			set
			{
				if ((this._IsShopped != value))
				{
					this.OnIsShoppedChanging(value);
					this.SendPropertyChanging();
					this._IsShopped = value;
					this.SendPropertyChanged("IsShopped");
					this.OnIsShoppedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="NVarChar(50)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(50)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SPBanResult
	{
		
		private string _TenSP;
		
		private System.Nullable<decimal> _DTBan;
		
		public SPBanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this._TenSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTBan", DbType="Money")]
		public System.Nullable<decimal> DTBan
		{
			get
			{
				return this._DTBan;
			}
			set
			{
				if ((this._DTBan != value))
				{
					this._DTBan = value;
				}
			}
		}
	}
	
	public partial class SPBanBDTronResult
	{
		
		private string _TenSP;
		
		private System.Nullable<decimal> _DTBan;
		
		public SPBanBDTronResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this._TenSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTBan", DbType="Money")]
		public System.Nullable<decimal> DTBan
		{
			get
			{
				return this._DTBan;
			}
			set
			{
				if ((this._DTBan != value))
				{
					this._DTBan = value;
				}
			}
		}
	}
	
	public partial class SPNhapResult
	{
		
		private string _TenSP;
		
		private System.Nullable<decimal> _DTNhap;
		
		public SPNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this._TenSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTNhap", DbType="Money")]
		public System.Nullable<decimal> DTNhap
		{
			get
			{
				return this._DTNhap;
			}
			set
			{
				if ((this._DTNhap != value))
				{
					this._DTNhap = value;
				}
			}
		}
	}
	
	public partial class SPNhapBDTronResult
	{
		
		private string _TenSP;
		
		private System.Nullable<decimal> _DTNhap;
		
		public SPNhapBDTronResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(50)")]
		public string TenSP
		{
			get
			{
				return this._TenSP;
			}
			set
			{
				if ((this._TenSP != value))
				{
					this._TenSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DTNhap", DbType="Money")]
		public System.Nullable<decimal> DTNhap
		{
			get
			{
				return this._DTNhap;
			}
			set
			{
				if ((this._DTNhap != value))
				{
					this._DTNhap = value;
				}
			}
		}
	}
	
	public partial class TienBanNamResult
	{
		
		private decimal _Thang1;
		
		private decimal _Thang2;
		
		private decimal _Thang3;
		
		private decimal _Thang4;
		
		private decimal _Thang5;
		
		private decimal _Thang6;
		
		private decimal _Thang7;
		
		private decimal _Thang8;
		
		private decimal _Thang9;
		
		private decimal _Thang10;
		
		private decimal _Thang11;
		
		private decimal _Thang12;
		
		public TienBanNamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang1", DbType="Money NOT NULL")]
		public decimal Thang1
		{
			get
			{
				return this._Thang1;
			}
			set
			{
				if ((this._Thang1 != value))
				{
					this._Thang1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang2", DbType="Money NOT NULL")]
		public decimal Thang2
		{
			get
			{
				return this._Thang2;
			}
			set
			{
				if ((this._Thang2 != value))
				{
					this._Thang2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang3", DbType="Money NOT NULL")]
		public decimal Thang3
		{
			get
			{
				return this._Thang3;
			}
			set
			{
				if ((this._Thang3 != value))
				{
					this._Thang3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang4", DbType="Money NOT NULL")]
		public decimal Thang4
		{
			get
			{
				return this._Thang4;
			}
			set
			{
				if ((this._Thang4 != value))
				{
					this._Thang4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang5", DbType="Money NOT NULL")]
		public decimal Thang5
		{
			get
			{
				return this._Thang5;
			}
			set
			{
				if ((this._Thang5 != value))
				{
					this._Thang5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang6", DbType="Money NOT NULL")]
		public decimal Thang6
		{
			get
			{
				return this._Thang6;
			}
			set
			{
				if ((this._Thang6 != value))
				{
					this._Thang6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang7", DbType="Money NOT NULL")]
		public decimal Thang7
		{
			get
			{
				return this._Thang7;
			}
			set
			{
				if ((this._Thang7 != value))
				{
					this._Thang7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang8", DbType="Money NOT NULL")]
		public decimal Thang8
		{
			get
			{
				return this._Thang8;
			}
			set
			{
				if ((this._Thang8 != value))
				{
					this._Thang8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang9", DbType="Money NOT NULL")]
		public decimal Thang9
		{
			get
			{
				return this._Thang9;
			}
			set
			{
				if ((this._Thang9 != value))
				{
					this._Thang9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang10", DbType="Money NOT NULL")]
		public decimal Thang10
		{
			get
			{
				return this._Thang10;
			}
			set
			{
				if ((this._Thang10 != value))
				{
					this._Thang10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang11", DbType="Money NOT NULL")]
		public decimal Thang11
		{
			get
			{
				return this._Thang11;
			}
			set
			{
				if ((this._Thang11 != value))
				{
					this._Thang11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang12", DbType="Money NOT NULL")]
		public decimal Thang12
		{
			get
			{
				return this._Thang12;
			}
			set
			{
				if ((this._Thang12 != value))
				{
					this._Thang12 = value;
				}
			}
		}
	}
	
	public partial class TienNhapNamResult
	{
		
		private decimal _Thang1;
		
		private decimal _Thang2;
		
		private decimal _Thang3;
		
		private decimal _Thang4;
		
		private decimal _Thang5;
		
		private decimal _Thang6;
		
		private decimal _Thang7;
		
		private decimal _Thang8;
		
		private decimal _Thang9;
		
		private decimal _Thang10;
		
		private decimal _Thang11;
		
		private decimal _Thang12;
		
		public TienNhapNamResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang1", DbType="Money NOT NULL")]
		public decimal Thang1
		{
			get
			{
				return this._Thang1;
			}
			set
			{
				if ((this._Thang1 != value))
				{
					this._Thang1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang2", DbType="Money NOT NULL")]
		public decimal Thang2
		{
			get
			{
				return this._Thang2;
			}
			set
			{
				if ((this._Thang2 != value))
				{
					this._Thang2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang3", DbType="Money NOT NULL")]
		public decimal Thang3
		{
			get
			{
				return this._Thang3;
			}
			set
			{
				if ((this._Thang3 != value))
				{
					this._Thang3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang4", DbType="Money NOT NULL")]
		public decimal Thang4
		{
			get
			{
				return this._Thang4;
			}
			set
			{
				if ((this._Thang4 != value))
				{
					this._Thang4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang5", DbType="Money NOT NULL")]
		public decimal Thang5
		{
			get
			{
				return this._Thang5;
			}
			set
			{
				if ((this._Thang5 != value))
				{
					this._Thang5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang6", DbType="Money NOT NULL")]
		public decimal Thang6
		{
			get
			{
				return this._Thang6;
			}
			set
			{
				if ((this._Thang6 != value))
				{
					this._Thang6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang7", DbType="Money NOT NULL")]
		public decimal Thang7
		{
			get
			{
				return this._Thang7;
			}
			set
			{
				if ((this._Thang7 != value))
				{
					this._Thang7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang8", DbType="Money NOT NULL")]
		public decimal Thang8
		{
			get
			{
				return this._Thang8;
			}
			set
			{
				if ((this._Thang8 != value))
				{
					this._Thang8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang9", DbType="Money NOT NULL")]
		public decimal Thang9
		{
			get
			{
				return this._Thang9;
			}
			set
			{
				if ((this._Thang9 != value))
				{
					this._Thang9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang10", DbType="Money NOT NULL")]
		public decimal Thang10
		{
			get
			{
				return this._Thang10;
			}
			set
			{
				if ((this._Thang10 != value))
				{
					this._Thang10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang11", DbType="Money NOT NULL")]
		public decimal Thang11
		{
			get
			{
				return this._Thang11;
			}
			set
			{
				if ((this._Thang11 != value))
				{
					this._Thang11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang12", DbType="Money NOT NULL")]
		public decimal Thang12
		{
			get
			{
				return this._Thang12;
			}
			set
			{
				if ((this._Thang12 != value))
				{
					this._Thang12 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
